---
output:
  pdf_document: default
  html_document: default
---
# Biosketches {#biosketches}

### BIOGRAPHICAL SKETCH
#### Francisco J. Guerrero - Researcher and Science Communicator
##### Personal statement
I am from Santa Marta, Colombia, one of the oldest cities in Latin America. I grew up in a community which, due to centuries-long social injustices, struggled to have access to basic necessities like drinking water. This was my main motivation to start my professional career in water resources. While pursuing a dual major Ph.D. in Forestry and Water Resources Science at Oregon State University (OSU), I started leading science communication efforts. Around this time, besides the regular SciComm workshops I would design and offer to graduate students at OSU, I had the rewarding opportunity to teach science storytelling to a diverse community of migrant children to inspire them to fall in love with science. The sense of connection with my own childhood through those kids is something that firmly imprinted itself in my memory and upon my heart.  These efforts in science communication resulted in my selection by the American Association for the Advancement of Science to be a Mass Media Fellow to work with CNN Español in 2018.  I also have continued working with underrepresented communities through a number of mentorship programs for both undergraduate and early career scientists in the U.S.
 
After my graduation from OSU I was selected as a Water Science-Policy Fellow at the University of Wisconsin-Madison. During my time in Wisconsin, I continued to engage in science communication activities. I developed science communication training materials for state agency staff and helped agency managers explore the role of knowledge brokers in synthesizing and articulating science to support policy formulation. I also had the opportunity to connect with several colleagues from the Life Science Communication Department at UW-Madison. 
 
Through my current position as a Science Communication Liaison for the National Center for Ecological Analysis and Synthesis (NCEAS) at UC Santa Barbara and COMPASS, I work with a vast network of scientists who, working at the cutting edge of data science, develop solutions to harmonize the relationship between people and nature. My job there includes the design and implementation of workshops on effective communication and engagement. I want to learn more, though. I want to walk the walk of engagement in order to become not only a more knowledgeable science communicator, but more importantly to construct and deliver value to those communities that are historically marginalized. 

Along my personal and professional journey I have persevered through the pressures of our academic system that forces us onto narrowing pathways, along which, very often, we must choose between doing either science or communication. I have chosen to interweave the two throughout my work with natural resources, which has resulted in amazing opportunities as a science communicator.

Education

* 2000 - 2005	University of Magdalena-Colombia, BS in aquatic biology
* 2007 - 2011	Pontifical Xavierian University-Colombia, M.Sc.hydrosystems
* 2013 - 2018 Oregon State University, Dual-major Ph.D. Sustainable Forest Management / Water Resources Science

Positions and Employment

* 2004 - 2005	Editorial Committee Assistant-Intropica Journal, University of Magdalena-Colombia
* 2006 - 2008	Research Assistant, Institute of Geophysics, Pontifical Xavierian University-Colombia
* 2008 - 2012	Director's Assistant, Engineering Doctoral Program, Pontifical Xavierian University-Colombia
* 2013 - 2018	Research Assistant, Forest Soils Lab, Oregon State University
* 2019 - 2020	Water Science-Policy Fellow- University of Wisconsin-Madison
* 2020 - present	Science Communication Liaison-National Center for Ecological Analysis and Synthesis and COMPASS Science Communication
* 2020 - present Courtesy Faculty Appointee, College of Forestry, Oregon State University

Other Experience

* 2007 - 2012 Water Resources Consultant (The Nature Conservancy, Ministry of Environment, Pontifical Xavierian University)
* 2009 - 2012 Graduate and Undergraduate Instructor in Water Resources Engineering (Pontifical Xavierian University, Catholic University of Colombia)
* 2014 - 2018 Workshop Designer and Instructor (LaRGE: Making your Presentations Likable, Reliable, and Gettable)-Oregon State University
* 2017        Trainer-Mentor at McCall Outdoor Science School (MOSS), Solar Science Program, University of Idaho.
* 2018        AAAS Mass Media Fellow at CNN en Espanol. 
* 2020 - Present Mentor for multicultural programs with ASLO and SFS

Most Recent Contribution: 

* Voter. C. B., Guerrero-Bolaño, F., A. Latzka, B. Maitland & J. Hauxwell. 2021. Adaptable University-Agency Early-Career Fellowship Program Creates a Win-Win-Win for Wisconsin’s Waters. Journal of Contemporary Water Research and Education.(Accepted for publication)

### BIOGRAPHICAL SKETCH
#### Liz Neeley - Founder and CEO of Liminal Creations LLC
##### Personal statement
In September 2020, I launched a new consulting firm focused on the sensemaking aspects of science communication. I felt compelled to do so by the catastrophic decision-making around me during the COVID pandemic. I saw how badly everyone, even science advocates, struggles to integrate science into their personal decision-making in moments of crisis. I have spent the past 15 years absorbing what academic research can tell us about things like risk perception, emotional decision-making, storytelling, and community deliberation. In this pandemic moment, I decided to act on my conviction that science communication is a survival skill for humanity. I named the firm Liminal to honor the process of emergence - that beautiful, difficult space we inhabit just before crossing the threshold from confusion into clarity. 
				
My current work uses sensemaking as its core framework. Sensemaking is the term we use to describe how people collect information, generate plausible accounts of what is happening, make decisions about the best course of action, and translate their experiences into future iterations of the cycle. I am particularly focused on the roles of narrative, identity, and persuasion in sensemaking efforts, and I work in this space both as a trainer and as a practitioner. Despite acute disincentives, I read the academic literature, contribute to formal peer review, and build collaborations with social scientists. Rather than publications, however, my primary products are performances, trainings, and relationships. I believe that informal networks and personal ties profoundly shape modern professional spaces, and am intimately familiar with the challenges of building communities online and in person.

All together, I have spent nearly fifteen years supporting scientists as they struggle with questions of how to communicate complexity and uncertainty, as well as where to draw personal/professional boundaries. The work I do now expands on that foundation and looks to a future where we knit together bodies of knowledge wherever we find them to help us all become safer, braver, and more generous in a complicated and chaotic world. 
 
Education

* 1998 - 2002	University of Maryland, BS in marine biology
* 2002 - 2005	Boston University, MA in ecology and evolution

Positions and Employment

* 2005 - 2006	Asia Pacific Program Associate, SeaWeb
* 2006 - 2008	International Coral Program Manager, SeaWeb
* 2008 - 2015	Assistant Director of Science Outreach, COMPASS
* 2010 - 2015	Affiliate Staff, University of Washington, College of the Environment
* 2015 - 2020	Executive Director, The Story Collider
* 2018 - present	Lecturer, Yale University, Department of Psychiatry
* 2021 - present	Senior Advisor for Science Communication, National Neuroscience Curriculum Initiative 

Other Experience 

* 2019 - 2021 Advisor, NPR SciCommers
* 2018 - 2019 Organizer, National Academy of Science Colloquium on the Science 	
	of Science Communication: Misinformation in the Public Sphere
* 2017 - 2019 Senior Advisor and Fiscal Sponsor, ComSciCon
* 2016 - 2018 Advisor, Ensia Magazine
* 2015 - 2018 Advisor, MIT CommLab
* 2012 - 2013	Organizer, ScienceOnline Climate
* 2012 - 2014 Founder, ScienceOnline Seattle
* 2010 - 2016 Advisor, ENGAGE, University of Washington

Selected contributions 

From 2005 to 2015, I focused on the nexus of ocean science, journalism, and policymaking. My contributions focused on extracting guiding principles for science communication from the literature and applying them in practice.

* Halpern et al. (2012) “An index to assess the health and benefits of the global ocean.” Nature 488(7413): 615–620.
* Baron (2010). Escape From the Ivory Tower: A guide to making your science matter. Washington DC, Island Press. (contributing author)
* Grorud-Colvert et al. (2010). “Communicating marine reserve science to diverse audiences.” Proceedings of the National Academy of Sciences 107(43).

Beginning in 2013, I focused on the challenges and opportunities that social media offers science communication, again working to ground new technologies in existing theory. I began to appreciate how narratives dominate popular understanding of current events.

* Neeley (2015) “Communicating Science in a Rapidly Changing World.” In Principles of Conservation Biology, 4th Edition, Sinauer Associates.
* McClain and Neeley (2014) “A critical evaluation of science outreach via social media: its role and impact on scientists” F1000 Research.
* Neeley (2013). “Risk Communication in Social Networks” In Risk Communication. Edited by Arvai and Rivers. London, Taylor & Francis.

From 2015 onward, I have focused on storytelling, narrative persuasion, and sense-making. I am particularly interested in how stories are used to understand events and social contexts, to imagine possible futures, and to position ourselves in the world. 

* Finlay et al. (2021) “From the Margins to the Mainstream: Deconstructing Science Communication as a White, Western Paradigm.” Journal of Science Communication 20, no. 1 
* Scheufele et al. (2021) “Misinformation about Science in the Public Sphere.” Proceedings of the National Academy of Sciences 118, no. 15
* Neeley et al. (2020) “Linking Scholarship and Practice: Narrative and Identity in Science.” Frontiers in Communication, 5.
* Gross et al. (2018) “Conservation Stories from the Front Lines.” PLOS Biology 16, no. 2: e2005226.

Research Support

National Science Foundation - Award ID 1255633 - 10/01/12 - 12/31/14. Culminated in GradSciComm: Mapping the Pathways to Integrate Science Communication Training into STEM Graduate Education, for which I was the lead author. 