# Outputs {#outputs}

The e-book [R for Data Science](https://r4ds.had.co.nz/) provides a model for our outputs, both in format and content. The book ends in a “Communicate” section, which we would expand into an “Engage” module. The assets generated by our project (e.g., texts, figures, visualizations, and code) will be hosted in the customizable Rmarkdown ecosystem of document authoring, and will be renderable as a stand-alone book section, among many other formats (e.g. HTML, pdfs, notebooks, etc). Both the book section and the source code will be available for users within the ARIS fellowship community as well as within our target audiences and anyone interested. Our content for the stand-alone book section will be organized in six short chapters:

* Engaging PEOPLE: A scalable communication infrastructure for broader impacts
* Engage to Ideate
* Engage to Experiment
* Engage to Analyze
* Engage to Report
* Engaging PEOPLE: Beyond the Lab

We will apply our own framework in the development of the $P^3$ framework and document the process, including network building with communities beyond the ARIS fellowship like [USGS Data Viz](https://on.doi.gov/3kR2T6Y), [OpenScapes](https://www.openscapes.org/), and more.  