# Overview {#overview}

Doing science in a world wracked by crises like climate change and COVID shifts public engagement efforts from vague commitments into urgent and personal practice. Unfortunately, for many researchers, neither the incentives for nor the impacts of broader impact efforts feel adequate to the global importance of such work [@rose2020]. This mismatch is complicated by the persistence of ‘deficit model’ approaches to science communication [@nadkarni2019], problematic assumptions about audiences, and the precarious nature of academic careers. Together, they produce a deficit-scarcity mindset: researchers feel increasingly troubled by public discourses, they experience frustration and/or helplessness with their inability to meaningfully shift those debates, and most of all, they feel there is no time for any work beyond the all-consuming need to produce scientific publications. To foster meaningful, impactful broader impacts work, we must therefore help researchers rebuild their sense of self-efficacy and strategic clarity.   

The open science movement offers us inspiration [@lowndes2017]. By unlocking multiple pathways for inclusive interactions with diverse groups of people along the entire research process, open science practices reduce delays and obstacles between knowledge production, sharing, and refinement. To date, most of the communication tools developed for open science focus on technical mechanics for the visual display of information and of sharing data and methods [@wickham2017]. The relational aspects of community building, as well as the strategic aspects of engagement, are largely disconnected from the tactical dimensions of information transfer. We think this represents an exciting opportunity.

To address priority 5: “Using evidence-based inclusive science communication principles in research impacts activities”, we propose an **extensible, self-guided, and scalable framework for strategic communication and engagement**. We are calling this framework $P^3 = PEOPLE, Products, and Pathways$. The term "*PEOPLE*" doubles in meaning here as an acronym for *P*oints of *E*ngagement *O*r *P*oints for *L*everaging *E*ngagement. We do so to emphasize the relational aspect of our proposed framework. This project is a collaboration between Dr. Francisco Guerrero and Liz Neeley, and and it is primarily focused on synthesis, with some new scholarship.

Our framework is inspired by Communication Infrastructure Theory as it describes the conditions that enable collective action for common purpose [@kim2006]. For infrastructure, we think of everyone and everything that a community needs to produce and support the rapidly expanding set of communication *Products* (data visualizations, interactive applications, web content managers) that are continuously opening new *Pathways* for sharing ideas and insights [@macarthur2020].Together, *PEOPLE*, *Products*, and *Pathways* constitute the core of a communication infrastructure that builds community and can achieve broader impacts if combined with science communication principles and practices.  

Our $P^3$ framework will guide users through a series of nested iterations of the engagement cycle [@nadkarni2019], and help them connect their impact identities as individuals to their broader impact activities as research teams or labs [@risien2018]. By providing an evidence-based guide and supporting structures for exploring their options, creating valid theories of change, and iterating on their strategies, we hope that our approach will shift our users’ thinking toward strategic, collective action. Such work should enhance both their perceived and real-world efficacy.

Our primary audiences are leaders of academic labs and anyone who is writing broader impact strategies, lab managers who oversee daily operations, and others who are focused on the praxis of broader impacts. We center these audiences because they wield institutional and positional power: they tend to create the systems and cultures that determine what actually happens within academic communities. 

We embrace the universal communications rule of meeting our audience where they are, so we will approach the work using the software tools research labs are using to analyze, visualize, and share data. We will develop and pilot the $P^3$ framework as an [Rmarkdown](https://rmarkdown.rstudio.com/) project that will be stored on GitHub and published with [BOOKDOWN](https://bookdown.org/). Our work will begin with creating the initial framework and workflow. We will then create the structures for curating resources to support decision-making at each step. Our initial product will address questions in our shared areas of skill, like how to use open-source code to support training, how to create narratives that welcome underrepresented communities, and how to share data to build and enhance partnerships.In each case we will highlight the *PEOPLE* involved in effective engagements, and the *Products* (i.e. messages + assets) that are often exchanged resulting in open *Pathways* (i.e. long-lasting interactions). 

