# Profiles {#profiles}

We met through our participation in the Science Communication Trainers Network, and discovered our mutual passion for relaying complex information in beautiful visuals. We found in each other a rare partner who values the academic literature about science communication just as much as the creative practice of expressing it. This project emerges from our long-term commitment to social justice and inclusive science, open science, and evidence-based science communication. 

We bring a wide variety of relevant skills: Guerrero serves as a knowlegdge broker into the scientific community employing coding, visualization, and scicomm skills, while Neeley brings six years of executive experience and intimately understands organizational information management and day-to-day practicalities of running an organization. Guerrero is currently working as Science Communication Liaison between the National Center for Ecological Analysis and Synthesis and COMPASS Science Communication. He is also a courtesy faculty with the College of Forestry at Oregon State University. Neeley also sits on the advisory boards of the Aspen Institute Program on Science and Society and the AAAS Committee on Science and Technology Engagement with the Public. Together, we count dozens if not hundreds of faculty, staff researchers, postdocs among our closest contacts. We have coached and earned the trust of hundreds, if not thousands, more. We intimately understand and deeply care about research and researchers both personally and professionally. It would be an honor and a privilege to earn an ARIS Fellowship to continue our work to support them. 